name: assignment
description: "Attendance Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.13
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.6
  path: ^1.8.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  location: ^7.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0  # For accessing device location
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  connectivity_plus: ^6.0.4
  package_info_plus: ^4.0.0
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/images/add.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
